In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv(r"C:\Users\LENOVO\Downloads\correct_twitter_201904.tsv",sep = "\t")
data

,id,event,ts1,ts2,from_stream,directly_from_stream,from_search,directly_from_search,from_quote_search,directly_from_quote_search,...,retweeted,retweeted_author_id,retweeted_handle,retweeted_follower_count,mentioned_author_ids,mentioned_handles,hashtags,urls,media_keys,place_id
0,1131594960443199488,britney_201904,2022-02-28 09:34:44.627023-05:00,2022-02-28 09:34:44.627023-05:00,True,True,False,False,False,False,...,1130917791752757254,3042894016,Iesbwian,22760,None,None,None,None,None,None
1,1131594976750653440,britney_201904,2022-02-28 09:34:44.626921-05:00,2022-02-28 09:34:44.626921-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,None,None,None
2,1131589737955942405,britney_201904,2022-02-28 09:34:44.634058-05:00,2022-02-28 09:34:44.634058-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,None,None,None
3,1131594909469892610,britney_201904,2022-02-28 09:34:44.627125-05:00,2022-02-28 09:34:44.627125-05:00,True,True,False,False,False,False,...,1130917791752757254,3042894016,Iesbwian,22760,None,None,None,None,None,None
4,1131594812694511617,britney_201904,2022-02-28 09:34:44.627227-05:00,2022-02-28 09:34:44.627227-05:00,True,True,False,False,False,False,...,1130917791752757254,3042894016,Iesbwian,22760,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88032,1122977274352082944,britney_201904,2022-02-28 09:47:43.066500-05:00,2022-02-28 09:47:43.066500-05:00,True,True,False,False,False,False,...,1122975837500989440,2934938957,STORMISKELLYBAG,13773,None,None,None,None,None,None
88033,1122977257969127429,britney_201904,2022-02-28 09:47:43.066605-05:00,2022-02-28 09:47:43.066605-05:00,True,True,False,False,False,False,...,1118942889785085958,613702825,keanuorange,1422,None,None,None,None,None,None
88034,1122977009347518466,britney_201904,2022-02-28 09:47:43.066708-05:00,2022-02-28 09:47:43.066708-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,None,None,None
88035,1122976878812442626,britney_201904,2022-02-28 09:47:43.066810-05:00,2022-02-28 09:47:43.066810-05:00,True,True,False,False,False,False,...,1122898327895519233,846864187015888896,TheBlastNews,11533,None,None,None,None,None,None
88036,1122976855647240203,britney_201904,2022-02-28 09:47:43.066921-05:00,2022-02-28 09:47:43.066921-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,"[{'end': 65, 'url': 'https://t.co/DcqjuqMJDK',...",None,None

In [9]:
data

,id,event,ts1,ts2,from_stream,directly_from_stream,from_search,directly_from_search,from_quote_search,directly_from_quote_search,...,retweeted,retweeted_author_id,retweeted_handle,retweeted_follower_count,mentioned_author_ids,mentioned_handles,hashtags,urls,media_keys,place_id
0,1131594960443199488,britney_201904,2022-02-28 09:34:44.627023-05:00,2022-02-28 09:34:44.627023-05:00,True,True,False,False,False,False,...,1130917791752757254,3042894016,Iesbwian,22760,None,None,None,None,None,None
1,1131594976750653440,britney_201904,2022-02-28 09:34:44.626921-05:00,2022-02-28 09:34:44.626921-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,None,None,None
2,1131589737955942405,britney_201904,2022-02-28 09:34:44.634058-05:00,2022-02-28 09:34:44.634058-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,None,None,None
3,1131594909469892610,britney_201904,2022-02-28 09:34:44.627125-05:00,2022-02-28 09:34:44.627125-05:00,True,True,False,False,False,False,...,1130917791752757254,3042894016,Iesbwian,22760,None,None,None,None,None,None
4,1131594812694511617,britney_201904,2022-02-28 09:34:44.627227-05:00,2022-02-28 09:34:44.627227-05:00,True,True,False,False,False,False,...,1130917791752757254,3042894016,Iesbwian,22760,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88032,1122977274352082944,britney_201904,2022-02-28 09:47:43.066500-05:00,2022-02-28 09:47:43.066500-05:00,True,True,False,False,False,False,...,1122975837500989440,2934938957,STORMISKELLYBAG,13773,None,None,None,None,None,None
88033,1122977257969127429,britney_201904,2022-02-28 09:47:43.066605-05:00,2022-02-28 09:47:43.066605-05:00,True,True,False,False,False,False,...,1118942889785085958,613702825,keanuorange,1422,None,None,None,None,None,None
88034,1122977009347518466,britney_201904,2022-02-28 09:47:43.066708-05:00,2022-02-28 09:47:43.066708-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,None,None,None
88035,1122976878812442626,britney_201904,2022-02-28 09:47:43.066810-05:00,2022-02-28 09:47:43.066810-05:00,True,True,False,False,False,False,...,1122898327895519233,846864187015888896,TheBlastNews,11533,None,None,None,None,None,None
88036,1122976855647240203,britney_201904,2022-02-28 09:47:43.066921-05:00,2022-02-28 09:47:43.066921-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,"[{'end': 65, 'url': 'https://t.co/DcqjuqMJDK',...",None,None

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88037 entries, 0 to 88036
Data columns (total 46 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             88037 non-null  int64
 1   event                          88037 non-null  object
 2   ts1                            88037 non-null  object
 3    ts2                           88037 non-null  object
 4   from_stream                    88037 non-null  bool
 5   directly_from_stream           88037 non-null  bool
 6   from_search                    88037 non-null  bool
 7   directly_from_search           88037 non-null  bool
 8   from_quote_search              88037 non-null  bool
 9   directly_from_quote_search     88037 non-null  bool
 10  from_convo_search              88037 non-null  bool
 11  directly_from_convo_search     88037 non-null  bool
 12  from_timeline_search           88037 non-null  bool
 13  directly_from_timeline_search  88037 non-null  bool
 14  text                           88037 non-null  object
 15  lang                           88037 non-null  object
 16  author_id                      88037 non-null  int64
 17  author_handle                  88037 non-null  object
 18  created_at                     88037 non-null  object
 19  conversation_id                88037 non-null  int64
 20  possibly_sensitive             88037 non-null  bool
 21  reply_settings                 88037 non-null  object
 22  source                         88037 non-null  object
 23  author_follower_count          88037 non-null  int64
 24  retweet_count                  88037 non-null  int64
 25  reply_count                    88037 non-null  int64
 26  like_count                     88037 non-null  int64
 27  quote_count                    88037 non-null  int64
 28  replied_to                     88037 non-null  object
 29  replied_to_author_id           88037 non-null  object
 30  replied_to_handle              88037 non-null  object
 31  replied_to_follower_count      88037 non-null  object
 32  quoted                         88037 non-null  object
 33  quoted_author_id               88037 non-null  object
 34  quoted_handle                  88037 non-null  object
 35  quoted_follower_count          88037 non-null  object
 36  retweeted                      88037 non-null  object
 37  retweeted_author_id            88037 non-null  object
 38  retweeted_handle               88037 non-null  object
 39  retweeted_follower_count       88037 non-null  object
 40  mentioned_author_ids           88037 non-null  object
 41  mentioned_handles              88037 non-null  object
 42  hashtags                       88037 non-null  object
 43  urls                           88037 non-null  object
 44  media_keys                     88037 non-null  object
 45  place_id                       88037 non-null  object
dtypes: bool(11), int64(8), object(27)
memory usage: 24.4+ MB

### Convert created_at Column to DateTime

In [11]:
data['created_at'] = pd.to_datetime(data['created_at'], utc=True, errors='coerce')
data

,id,event,ts1,ts2,from_stream,directly_from_stream,from_search,directly_from_search,from_quote_search,directly_from_quote_search,...,retweeted,retweeted_author_id,retweeted_handle,retweeted_follower_count,mentioned_author_ids,mentioned_handles,hashtags,urls,media_keys,place_id
0,1131594960443199488,britney_201904,2022-02-28 09:34:44.627023-05:00,2022-02-28 09:34:44.627023-05:00,True,True,False,False,False,False,...,1130917791752757254,3042894016,Iesbwian,22760,None,None,None,None,None,None
1,1131594976750653440,britney_201904,2022-02-28 09:34:44.626921-05:00,2022-02-28 09:34:44.626921-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,None,None,None
2,1131589737955942405,britney_201904,2022-02-28 09:34:44.634058-05:00,2022-02-28 09:34:44.634058-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,None,None,None
3,1131594909469892610,britney_201904,2022-02-28 09:34:44.627125-05:00,2022-02-28 09:34:44.627125-05:00,True,True,False,False,False,False,...,1130917791752757254,3042894016,Iesbwian,22760,None,None,None,None,None,None
4,1131594812694511617,britney_201904,2022-02-28 09:34:44.627227-05:00,2022-02-28 09:34:44.627227-05:00,True,True,False,False,False,False,...,1130917791752757254,3042894016,Iesbwian,22760,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88032,1122977274352082944,britney_201904,2022-02-28 09:47:43.066500-05:00,2022-02-28 09:47:43.066500-05:00,True,True,False,False,False,False,...,1122975837500989440,2934938957,STORMISKELLYBAG,13773,None,None,None,None,None,None
88033,1122977257969127429,britney_201904,2022-02-28 09:47:43.066605-05:00,2022-02-28 09:47:43.066605-05:00,True,True,False,False,False,False,...,1118942889785085958,613702825,keanuorange,1422,None,None,None,None,None,None
88034,1122977009347518466,britney_201904,2022-02-28 09:47:43.066708-05:00,2022-02-28 09:47:43.066708-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,None,None,None
88035,1122976878812442626,britney_201904,2022-02-28 09:47:43.066810-05:00,2022-02-28 09:47:43.066810-05:00,True,True,False,False,False,False,...,1122898327895519233,846864187015888896,TheBlastNews,11533,None,None,None,None,None,None
88036,1122976855647240203,britney_201904,2022-02-28 09:47:43.066921-05:00,2022-02-28 09:47:43.066921-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,"[{'end': 65, 'url': 'https://t.co/DcqjuqMJDK',...",None,None

### Filter Tweets Containing a Search Term

In [12]:
search_term = "music"
data_filtered = data[data['text'].str.contains(search_term, case=False, na=False)]
data_filtered

,id,event,ts1,ts2,from_stream,directly_from_stream,from_search,directly_from_search,from_quote_search,directly_from_quote_search,...,retweeted,retweeted_author_id,retweeted_handle,retweeted_follower_count,mentioned_author_ids,mentioned_handles,hashtags,urls,media_keys,place_id
89,1131558142569959424,britney_201904,2022-02-28 09:34:49.489632-05:00,2022-02-28 09:34:49.489632-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,None,None,None,None
191,1134153062384357378,britney_201904,2022-01-04 15:45:46.545877-05:00,2022-02-28 09:32:01.642704-05:00,True,True,False,False,False,False,...,1134149665606307841,4872315238,Bryan_KnowsBest,308,None,None,None,None,None,None
275,1130933441191710720,britney_201904,2022-01-04 15:46:39.404655-05:00,2022-02-28 09:35:43.998377-05:00,True,True,False,False,False,False,...,1130654444495020032,16339785,musicdotjunkee,32389,None,None,['FreeBritney'],None,None,None
339,1129818710095613952,britney_201904,2022-01-04 15:47:01.723682-05:00,2022-02-28 09:37:33.446307-05:00,True,True,False,False,False,False,...,1128705303862808577,1030185143460397058,EatPrayBritney,9329,None,None,None,None,None,None
341,1128705303862808577,britney_201904,2022-01-04 15:47:01.748329-05:00,2022-02-28 09:40:48.913892-05:00,True,True,False,False,False,False,...,None,None,None,None,None,None,['FREEBRITNEY'],None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87942,1122966243596820481,britney_201904,2022-02-28 09:47:43.076588-05:00,2022-02-28 09:47:43.076588-05:00,True,True,False,False,False,False,...,1122898327895519233,846864187015888896,TheBlastNews,11533,None,None,None,None,None,None
87950,1122964762617352193,britney_201904,2022-02-28 09:47:43.077468-05:00,2022-02-28 09:47:43.077468-05:00,True,True,False,False,False,False,...,1122898327895519233,846864187015888896,TheBlastNews,11533,None,None,None,None,None,None
87975,1122956541760503809,britney_201904,2022-02-28 09:47:43.083885-05:00,2022-02-28 09:47:43.083885-05:00,True,True,False,False,False,False,...,1122898327895519233,846864187015888896,TheBlastNews,11533,None,None,None,None,None,None
88020,1122955608356007936,britney_201904,2022-02-28 09:47:43.096550-05:00,2022-02-28 09:47:43.096550-05:00,True,False,False,False,False,False,...,None,None,None,None,None,None,None,None,None,None
88035,1122976878812442626,britney_201904,2022-02-28 09:47:43.066810-05:00,2022-02-28 09:47:43.066810-05:00,True,True,False,False,False,False,...,1122898327895519233,846864187015888896,TheBlastNews,11533,None,None,None,None,None,None

## Answer the Query Requirements

### tweets_per_day

In [13]:
tweets_per_day = data_filtered.groupby(data_filtered['created_at'].dt.date)['id'].count()
print(tweets_per_day)

created_at
2019-03-12      3
2019-04-06      1
2019-04-14      1
2019-04-16      1
2019-04-21      1
2019-04-24      1
2019-04-26      1
2019-04-27      3
2019-04-28     22
2019-04-29    118
2019-04-30    135
2019-05-01     71
2019-05-02     72
2019-05-03    103
2019-05-04     75
2019-05-05     65
2019-05-06     71
2019-05-07     64
2019-05-08     60
2019-05-09     70
2019-05-10    307
2019-05-11     78
2019-05-12     69
2019-05-13     50
2019-05-14     67
2019-05-15     99
2019-05-16     91
2019-05-17    162
2019-05-18     61
2019-05-19     46
2019-05-20     64
2019-05-21    119
2019-05-22     80
2019-05-23     73
2019-05-24     49
2019-05-25     92
2019-05-26    112
2019-05-27     76
2019-05-28     96
2019-05-29    187
2019-05-30     71
2019-05-31     14
Name: id, dtype: int64

### Number of unique users posting tweets

In [16]:
unique_users = data_filtered['author_id'].nunique()
print(unique_users)

2109

### Average likes for tweets

In [17]:
average_likes = data_filtered['like_count'].mean()
print(average_likes)

161.40853048983672

### Place IDs where tweets originated

In [19]:
place_ids = data_filtered['place_id'].dropna().unique()
print(place_ids)

['None' '53504716d445dcad' 'ab2f2fac83aa388d' '0113afc024d5e0bc'
 '300bcc6e23a88361' '8e9665cec9370f0f' 'd56c5babcffde8ef'
 '01153d1b33e1641b' '09f6a7707f18e0b1' '714789cf3b7a50d0'
 '01fbe706f872cb32' '1a7a70d4a28e96a1' 'f97108ab3c4a42ed'
 'ac88a4f17a51c7fc' '5de8cffc145c486b' '3f7a925ec706ea48'
 '001aff55522d96c9' '4c8e28554110ebcf' '5c62ffb0f0f3479d'
 '3b77caf94bfc81fe' 'ecbe2aea853af44e' 'de599025180e2ee7'
 '00b673715a35dfa7' '43d2418301bf1a49' '07e9c7d1954fff64'
 '0570f015c264cbd9' '0149775319466b18' '91890dbb74364d63'
 '01ddb0100b1efd97' 'b49b3053b5c25bf5' '7cb7440bcf83d464'
 '151b9e91272233d1' '9d63050d3d33d32f' '140800566259f12f'
 '743df94d8dcb69a6' '8bc4eeacf63235f9' '8943f93b51e3f357'
 '2bc7c264a080898b' '814cfc71b843ff40' '2b8922cbe7f16337'
 '7de31e05e99a00f8']

### Times of day when the tweets were posted

In [20]:
tweets_time_of_day = data_filtered.groupby(data_filtered['created_at'].dt.hour)['id'].count()
print(tweets_time_of_day)

created_at
0     159
1     154
2     166
3     155
4     135
5     119
6      89
7      85
8      99
9      94
10     70
11     55
12    107
13    130
14    151
15    147
16    122
17    137
18    152
19    163
20    120
21    110
22    146
23    136
Name: id, dtype: int64

### User who posted the most tweets containing the term

In [21]:
top_user = data_filtered['author_handle'].value_counts().idxmax()
print(top_user)

freqnetwork

## Overall Required Analysis

In [24]:
# Load data
data = pd.read_csv(r"C:\Users\LENOVO\Downloads\correct_twitter_201904.tsv", sep='\t')

# Convert created_at to datetime
data['created_at'] = pd.to_datetime(data['created_at'], utc=True, errors='coerce')
print(data.head(10))
print("-----------------------------------------------------------------------------------------------------")

# Search term filter
search_term = "music"
data_filtered = data[data['text'].str.contains(search_term, case=False, na=False)]
print(data_filtered)
print("-----------------------------------------------------------------------------------------------------")

# 1. Tweets per day
tweets_per_day = data_filtered.groupby(data_filtered['created_at'].dt.date)['id'].count()
print("Tweets per day:", tweets_per_day)
print("-----------------------------------------------------------------------------------------------------")

# 2. Unique users
unique_users = data_filtered['author_id'].nunique()
print("Unique users:", unique_users)
print("-----------------------------------------------------------------------------------------------------")

# 3. Average likes
average_likes = data_filtered['like_count'].mean()
print("Average likes:", average_likes)
print("-----------------------------------------------------------------------------------------------------")

# 4. Place IDs
place_ids = data_filtered['place_id'].dropna().unique()
print("Place IDs:", place_ids)
print("-----------------------------------------------------------------------------------------------------")

# 5. Times of day
tweets_time_of_day = data_filtered.groupby(data_filtered['created_at'].dt.hour)['id'].count()
print("Times of day:", tweets_time_of_day)
print("-----------------------------------------------------------------------------------------------------")

# 6. Top user
top_user = data_filtered['author_handle'].value_counts().idxmax()
print("Top user:", top_user)

                    id           event                               ts1  \
0  1131594960443199488  britney_201904  2022-02-28 09:34:44.627023-05:00
1  1131594976750653440  britney_201904  2022-02-28 09:34:44.626921-05:00
2  1131589737955942405  britney_201904  2022-02-28 09:34:44.634058-05:00
3  1131594909469892610  britney_201904  2022-02-28 09:34:44.627125-05:00
4  1131594812694511617  britney_201904  2022-02-28 09:34:44.627227-05:00
5  1131594782969683974  britney_201904  2022-02-28 09:34:44.627329-05:00
6  1131589775226482688  britney_201904  2022-02-28 09:34:44.633954-05:00
7  1131585773424144384  britney_201904  2022-02-28 09:34:49.455116-05:00
8  1131583130572328961  britney_201904  2022-02-28 09:34:49.459955-05:00
9  1131581469384728578  britney_201904  2022-02-28 09:34:49.462612-05:00

                                ts2  from_stream  directly_from_stream  \
0  2022-02-28 09:34:44.627023-05:00         True                  True
1  2022-02-28 09:34:44.626921-05:00         True                  True
2  2022-02-28 09:34:44.634058-05:00         True                  True
3  2022-02-28 09:34:44.627125-05:00         True                  True
4  2022-02-28 09:34:44.627227-05:00         True                  True
5  2022-02-28 09:34:44.627329-05:00         True                  True
6  2022-02-28 09:34:44.633954-05:00         True                  True
7  2022-02-28 09:34:49.455116-05:00         True                  True
8  2022-02-28 09:34:49.459955-05:00         True                  True
9  2022-02-28 09:34:49.462612-05:00         True                  True

   from_search  directly_from_search  from_quote_search  \
0        False                 False              False
1        False                 False              False
2        False                 False              False
3        False                 False              False
4        False                 False              False
5        False                 False              False
6        False                 False              False
7        False                 False              False
8        False                 False              False
9        False                 False              False

   directly_from_quote_search  ...            retweeted  retweeted_author_id  \
0                       False  ...  1130917791752757254           3042894016
1                       False  ...                 None                 None
2                       False  ...                 None                 None
3                       False  ...  1130917791752757254           3042894016
4                       False  ...  1130917791752757254           3042894016
5                       False  ...  1130917791752757254           3042894016
6                       False  ...  1130917791752757254           3042894016
7                       False  ...  1130917791752757254           3042894016
8                       False  ...  1130917791752757254           3042894016
9                       False  ...  1130917791752757254           3042894016

   retweeted_handle  retweeted_follower_count mentioned_author_ids  \
0          Iesbwian                     22760                 None
1              None                      None                 None
2              None                      None                 None
3          Iesbwian                     22760                 None
4          Iesbwian                     22760                 None
5          Iesbwian                     22760                 None
6          Iesbwian                     22760                 None
7          Iesbwian                     22760                 None
8          Iesbwian                     22760                 None
9          Iesbwian                     22760                 None

  mentioned_handles  hashtags  urls media_keys  place_id
0              None      None  None       None      None
1              None      None  None       None      None
2              None      None  None       None      None
3              None      None  None       None      None
4              None      None  None       None      None
5              None      None  None       None      None
6              None      None  None       None      None
7              None      None  None       None      None
8              None      None  None       None      None
9              None      None  None       None      None

[10 rows x 46 columns]
-----------------------------------------------------------------------------------------------------
                        id           event                               ts1  \
89     1131558142569959424  britney_201904  2022-02-28 09:34:49.489632-05:00
191    1134153062384357378  britney_201904  2022-01-04 15:45:46.545877-05:00
275    1130933441191710720  britney_201904  2022-01-04 15:46:39.404655-05:00
339    1129818710095613952  britney_201904  2022-01-04 15:47:01.723682-05:00
341    1128705303862808577  britney_201904  2022-01-04 15:47:01.748329-05:00
...                    ...             ...                               ...
87942  1122966243596820481  britney_201904  2022-02-28 09:47:43.076588-05:00
87950  1122964762617352193  britney_201904  2022-02-28 09:47:43.077468-05:00
87975  1122956541760503809  britney_201904  2022-02-28 09:47:43.083885-05:00
88020  1122955608356007936  britney_201904  2022-02-28 09:47:43.096550-05:00
88035  1122976878812442626  britney_201904  2022-02-28 09:47:43.066810-05:00

                                    ts2  from_stream  directly_from_stream  \
89     2022-02-28 09:34:49.489632-05:00         True                  True
191    2022-02-28 09:32:01.642704-05:00         True                  True
275    2022-02-28 09:35:43.998377-05:00         True                  True
339    2022-02-28 09:37:33.446307-05:00         True                  True
341    2022-02-28 09:40:48.913892-05:00         True                  True
...                                 ...          ...                   ...
87942  2022-02-28 09:47:43.076588-05:00         True                  True
87950  2022-02-28 09:47:43.077468-05:00         True                  True
87975  2022-02-28 09:47:43.083885-05:00         True                  True
88020  2022-02-28 09:47:43.096550-05:00         True                 False
88035  2022-02-28 09:47:43.066810-05:00         True                  True

       from_search  directly_from_search  from_quote_search  \
89           False                 False              False
191          False                 False              False
275          False                 False              False
339          False                 False              False
341          False                 False              False
...            ...                   ...                ...
87942        False                 False              False
87950        False                 False              False
87975        False                 False              False
88020        False                 False              False
88035        False                 False              False

       directly_from_quote_search  ...            retweeted  \
89                          False  ...                 None
191                         False  ...  1134149665606307841
275                         False  ...  1130654444495020032
339                         False  ...  1128705303862808577
341                         False  ...                 None
...                           ...  ...                  ...
87942                       False  ...  1122898327895519233
87950                       False  ...  1122898327895519233
87975                       False  ...  1122898327895519233
88020                       False  ...                 None
88035                       False  ...  1122898327895519233

       retweeted_author_id  retweeted_handle  retweeted_follower_count  \
89                    None              None                      None
191             4872315238   Bryan_KnowsBest                       308
275               16339785    musicdotjunkee                     32389
339    1030185143460397058    EatPrayBritney                      9329
341                   None              None                      None
...                    ...               ...                       ...
87942   846864187015888896      TheBlastNews                     11533
87950   846864187015888896      TheBlastNews                     11533
87975   846864187015888896      TheBlastNews                     11533
88020                 None              None                      None
88035   846864187015888896      TheBlastNews                     11533

      mentioned_author_ids mentioned_handles         hashtags  urls  \
89                    None              None             None  None
191                   None              None             None  None
275                   None              None  ['FreeBritney']  None
339                   None              None             None  None
341                   None              None  ['FREEBRITNEY']  None
...                    ...               ...              ...   ...
87942                 None              None             None  None
87950                 None              None             None  None
87975                 None              None             None  None
88020                 None              None             None  None
88035                 None              None             None  None

      media_keys  place_id
89          None      None
191         None      None
275         None      None
339         None      None
341         None      None
...          ...       ...
87942       None      None
87950       None      None
87975       None      None
88020       None      None
88035       None      None

[3001 rows x 46 columns]
-----------------------------------------------------------------------------------------------------
Tweets per day: created_at
2019-03-12      3
2019-04-06      1
2019-04-14      1
2019-04-16      1
2019-04-21      1
2019-04-24      1
2019-04-26      1
2019-04-27      3
2019-04-28     22
2019-04-29    118
2019-04-30    135
2019-05-01     71
2019-05-02     72
2019-05-03    103
2019-05-04     75
2019-05-05     65
2019-05-06     71
2019-05-07     64
2019-05-08     60
2019-05-09     70
2019-05-10    307
2019-05-11     78
2019-05-12     69
2019-05-13     50
2019-05-14     67
2019-05-15     99
2019-05-16     91
2019-05-17    162
2019-05-18     61
2019-05-19     46
2019-05-20     64
2019-05-21    119
2019-05-22     80
2019-05-23     73
2019-05-24     49
2019-05-25     92
2019-05-26    112
2019-05-27     76
2019-05-28     96
2019-05-29    187
2019-05-30     71
2019-05-31     14
Name: id, dtype: int64
-----------------------------------------------------------------------------------------------------
Unique users: 2109
-----------------------------------------------------------------------------------------------------
Average likes: 161.40853048983672
-----------------------------------------------------------------------------------------------------
Place IDs: ['None' '53504716d445dcad' 'ab2f2fac83aa388d' '0113afc024d5e0bc'
 '300bcc6e23a88361' '8e9665cec9370f0f' 'd56c5babcffde8ef'
 '01153d1b33e1641b' '09f6a7707f18e0b1' '714789cf3b7a50d0'
 '01fbe706f872cb32' '1a7a70d4a28e96a1' 'f97108ab3c4a42ed'
 'ac88a4f17a51c7fc' '5de8cffc145c486b' '3f7a925ec706ea48'
 '001aff55522d96c9' '4c8e28554110ebcf' '5c62ffb0f0f3479d'
 '3b77caf94bfc81fe' 'ecbe2aea853af44e' 'de599025180e2ee7'
 '00b673715a35dfa7' '43d2418301bf1a49' '07e9c7d1954fff64'
 '0570f015c264cbd9' '0149775319466b18' '91890dbb74364d63'
 '01ddb0100b1efd97' 'b49b3053b5c25bf5' '7cb7440bcf83d464'
 '151b9e91272233d1' '9d63050d3d33d32f' '140800566259f12f'
 '743df94d8dcb69a6' '8bc4eeacf63235f9' '8943f93b51e3f357'
 '2bc7c264a080898b' '814cfc71b843ff40' '2b8922cbe7f16337'
 '7de31e05e99a00f8']
-----------------------------------------------------------------------------------------------------
Times of day: created_at
0     159
1     154
2     166
3     155
4     135
5     119
6      89
7      85
8      99
9      94
10     70
11     55
12    107
13    130
14    151
15    147
16    122
17    137
18    152
19    163
20    120
21    110
22    146
23    136
Name: id, dtype: int64
-----------------------------------------------------------------------------------------------------
Top user: freqnetwork